from .llama import LlamaAWQForCausalLM
from .mistral import MistralAWQForCausalLM
from .llava import LlavaAWQForCausalLM
from .mixtral import MixtralAWQForCausalLM
from .qwen2 import Qwen2AWQForCausalLM
from .qwen3 import Qwen3AWQForCausalLM
from .qwen3_moe import Qwen3MoeAWQForCausalLM
from .gemma2 import Gemma2AWQForCausalLM
from .llava_next import LlavaNextAWQForCausalLM
from .phi3 import Phi3AWQForCausalLM
from .phi3_v import Phi3VAWQForCausalLM
from .deepseek_v3 import DeepseekV3AWQForCausalLM
from .qwen2vl import Qwen2VLAWQForCausalLM
from .qwen2_5_vl import Qwen2_5_VLAWQForCausalLM
from .qwen2_5_omni import Qwen2_5_OmniAWQForConditionalGeneration